project_id = "vmosorcezhoqunpbfobf"

[functions.generate-video]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
